import { cosUsesMfo12OnlyIpcr, getIndicatorDef, hasTargetInput } from "@/lib/evaluation-client";
import { isIncludedInRatingPeriod } from "@/lib/indicator-period";
import type { FullEvaluationResult } from "@/lib/calculation-engine/evaluation";
import type { EvaluationState } from "@/lib/types";
import { RULESET_VERSION } from "@/data/reference";
import { formatRating, APP_DISPLAY_NAME } from "@/lib/utils";

export interface WorksheetIndicatorRow {
  name: string;
  mfo: string;
  rating: string;
}

export interface WorksheetTargetRow {
  type: string;
  statement: string;
  target: string;
  actual: string;
}

export interface WorksheetData {
  title: string;
  subtitle: string;
  facultyRows: [string, string][];
  indicators: WorksheetIndicatorRow[];
  targets: WorksheetTargetRow[];
  summaryRows: [string, string][];
  finalRating: string;
  adjectivalRating: string;
  footerNote: string;
}

export function buildWorksheetData(
  state: EvaluationState,
  computation: FullEvaluationResult
): WorksheetData {
  const { profile } = state;

  const facultyRows: [string, string][] = [
    ["Faculty Member", profile.facultyName || "—"],
    ["Academic Rank", profile.academicRankTitle || "—"],
    ["College", profile.collegeName || "—"],
    ["Appointment", profile.appointmentType.replace(/_/g, " ")],
    ["Evaluation Year / Period", `${profile.evaluationYear} — ${profile.ratingPeriod}`],
    ["Teaching Load", `${profile.teachingLoadUnits} units`],
  ];

  if (profile.hasDesignation) {
    facultyRows.push(
      ["Designation", profile.designationTitle || "—"],
      ["Deloaded Units", String(profile.deloadedUnits)],
      ["Office Order Verified", profile.officeOrderVerified ? "Yes" : "No"]
    );
  }

  const indicators = state.indicators
    .filter((e) => e.applicabilityStatus === "APPLICABLE")
    .map((entry) => {
      const def = getIndicatorDef(entry.code);
      const result = computation.indicatorRatings[entry.code];
      const included = isIncludedInRatingPeriod(entry);
      return {
        name: def?.name ?? entry.code,
        mfo: def?.mfoCode ?? "—",
        rating: included ? formatRating(result?.rating) : "N/A",
      };
    });

  const targets: WorksheetTargetRow[] = [
    ...state.strategicTargets.filter(hasTargetInput).map((t) => ({
      type: "Strategic",
      statement: t.targetStatement || "—",
      target: String(t.periodTarget),
      actual: String(t.actualAccomplishment ?? "—"),
    })),
    ...state.priorityTargets.filter(hasTargetInput).map((t) => ({
      type: "Priority",
      statement: t.targetStatement || "—",
      target: String(t.periodTarget),
      actual: String(t.actualAccomplishment ?? "—"),
    })),
  ];

  const mfo12Only = cosUsesMfo12OnlyIpcr(state);

  const summaryRows: [string, string][] = [
    ["Performance Results", formatRating(computation.performanceResults.rating)],
    [
      "Strategic/Priority (combined)",
      mfo12Only ? "N/A" : formatRating(computation.consolidatedStratPri.rating),
    ],
    ["Base IPCR", formatRating(computation.baseIpcr.rating)],
    ["Final IPCR", formatRating(computation.finalIpcr.rating)],
    ["Adjectival Rating", computation.adjectivalRating],
  ];

  if (profile.hasSupportFunctions) {
    summaryRows.splice(2, 0, [
      "Support Functions",
      formatRating(computation.supportFunctionsRating.rating),
    ]);
  }

  if (profile.hasDesignation) {
    summaryRows.splice(summaryRows.length - 2, 0, [
      "Designation Rating",
      formatRating(computation.designationRating.rating),
    ]);
  }

  return {
    title: "ParSU IPCR Rating Summary / Evaluation Worksheet",
    subtitle: RULESET_VERSION,
    facultyRows,
    indicators,
    targets,
    summaryRows,
    finalRating: formatRating(computation.finalIpcr.rating),
    adjectivalRating: computation.adjectivalRating,
    footerNote:
      `Generated by the ${APP_DISPLAY_NAME} for rating computation purposes only. ` +
      "Means of Verification are reference guidance and are not attached. Subject to official " +
      "approval and signing.",
  };
}

export function buildExportFilename(facultyName: string): string {
  const prefix = facultyName.slice(0, 10);
  return `${prefix || "Faculty"}-IPCR Eval Sheet.pdf`;
}
